import { NotifyTrigger } from '@coveo/headless';
import { InitializableComponent } from '../../../utils/initialization-utils';
import { Bindings } from '../atomic-search-interface/atomic-search-interface';
/**
 * The `atomic-notifications` component is responsible for displaying notifications generated by the Coveo Search API (see [Trigger](https://docs.coveo.com/en/1458)).
 *
 * @part notifications - The wrapper around the notifications.
 * @part notification - The wrapper around a single notification.
 * @part icon - The icon of the notification.
 * @part text - The text of the notification.
 */
export declare class AtomicNotifyTrigger implements InitializableComponent {
    bindings: Bindings;
    protected notifyTrigger: NotifyTrigger;
    private notifyTriggerState?;
    error: Error;
    ariaMessage: string;
    /**
     * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use above the notifications, from 1 to 6.
     */
    headingLevel: number;
    /**
     * Specifies an icon to display at the left-end of a notification.
     *
     * - Use a value that starts with `http://`, `https://`, `./`, or `../`, to fetch and display an icon from a given location.
     * - Use a value that starts with `assets://`, to display an icon from the Atomic package.
     * - Use a stringified SVG to display it directly
     */
    icon?: string;
    initialize(): void;
    generateAriaMessage(): string;
    renderNotification(text: string): any;
    renderNotifications(): any;
    render(): any;
    private get notifications();
}
