import { PlatformEnvironment, LogLevel, CommerceEngine, CommerceEngineConfiguration } from '@coveo/headless/commerce';
import { i18n } from 'i18next';
import { InitializeEvent } from '../../../utils/initialization-utils';
import { CommonBindings, NonceBindings } from '../../common/interface/bindings';
import { BaseAtomicInterface } from '../../common/interface/interface-common';
import { AtomicCommerceStore } from './store';
export type CommerceInitializationOptions = CommerceEngineConfiguration;
export type CommerceBindings = CommonBindings<CommerceEngine, AtomicCommerceStore, HTMLAtomicCommerceInterfaceElement> & NonceBindings;
/**
 * @internal
 * The `atomic-commerce-interface` component is the parent to all other atomic commerce components in a commerce page. It handles the headless search engine and localization configurations.
 */
export declare class AtomicCommerceInterface implements BaseAtomicInterface<CommerceEngine> {
    private urlManager;
    private searchStatus;
    private unsubscribeUrlManager;
    private unsubscribeSearchStatus;
    private initialized;
    private store;
    private commonInterfaceHelper;
    host: HTMLAtomicCommerceInterfaceElement;
    error?: Error;
    /**
     * The type of the interface.
     * - 'search': Indicates that the interface is used for Search.
     * - 'product-listing': Indicates that the interface is used for Product listing.
     */
    type: 'search' | 'product-listing' | 'recommendations';
    /**
     * Whether analytics should be enabled.
     */
    analytics: boolean;
    /**
     * The severity level of the messages to log in the console.
     */
    logLevel?: LogLevel;
    /**
     * the commerce interface i18next instance.
     */
    i18n: i18n;
    /**
     * the commerce interface language.
     */
    language: string;
    /**
     * The commerce interface headless engine.
     */
    engine?: CommerceEngine;
    /**
     * Whether the state should be reflected in the URL parameters.
     */
    reflectStateInUrl: boolean;
    /**
     * The CSS selector for the container where the interface will scroll back to.
     */
    scrollContainer: string;
    /**
     * The language assets path. By default, this will be a relative URL pointing to `./lang`.
     *
     * Example: "/mypublicpath/languages"
     *
     */
    languageAssetsPath: string;
    /**
     * The icon assets path. By default, this will be a relative URL pointing to `./assets`.
     *
     * Example: "/mypublicpath/icons"
     *
     */
    iconAssetsPath: string;
    /**
     * The value to set the [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce) attribute to on inline script and style elements generated by this interface and its child components.
     * If your application is served with a Content Security Policy (CSP) that doesn't include the `script-src: 'unsafe-inline'` or `style-src: 'unsafe-inline'` directives,
     * you should ensure that your application server generates a new nonce on every page load and uses the generated value to set this prop and serve the corresponding CSP response headers
     * (i.e., script-src 'nonce-<YOUR_GENERATED_NONCE>' and style-src 'nonce-<YOUR_GENERATED_NONCE>').
     * Otherwise you may see console errors such as
     *  - Refused to execute inline script because it violates the following Content Security Policy directive: [...]
     *  - Refused to apply inline style because it violates the following Content Security Policy directive: [...].
     * @example:
     * ```html
     * <script nonce="<YOUR_GENERATED_NONCE>">
     *  import {setNonce} from '@coveo/atomic';
     *  setNonce('<YOUR_GENERATED_NONCE>');
     * </script>
     * ```
     */
    CspNonce?: string;
    /**
     * A reference clone of the interface i18next instance.
     */
    private i18nClone;
    constructor();
    connectedCallback(): void;
    componentWillLoad(): void;
    toggleAnalytics(): void;
    updateLanguage(): void;
    updateIconAssetsPath(): void;
    disconnectedCallback(): void;
    handleInitialization(event: InitializeEvent): void;
    scrollToTop(): void;
    /**
     * Initializes the connection with the headless search engine using options for accessToken (required), organizationId (required), renewAccessToken, organizationEndpoints (recommended), and platformUrl (deprecated).
     */
    initialize(options: CommerceInitializationOptions): Promise<void>;
    /**
     * Initializes the connection with an already preconfigured [headless search engine](https://docs.coveo.com/en/headless/latest/reference/search/), as opposed to the `initialize` method, which will internally create a new search engine instance.
     * This bypasses the properties set on the component, such as analytics, searchHub, pipeline, language, timezone & logLevel.
     */
    initializeWithEngine(engine: CommerceEngine): Promise<void>;
    /**
     *
     * Executes the first search after initializing connection to the headless search engine.
     */
    executeFirstSearch(): Promise<void>;
    /**
     * Returns the unique, organization-specific endpoint(s).
     * @param {string} organizationId
     * @param {'prod'|'hipaa'|'staging'|'dev'} [env=Prod]
     */
    getOrganizationEndpoints(organizationId: string, env?: PlatformEnvironment): Promise<{
        platform: string;
        analytics: string;
        search: string;
        admin: string;
    }>;
    get bindings(): CommerceBindings;
    private initEngine;
    private get fragment();
    private initAriaLive;
    private initUrlManager;
    private initSearchStatus;
    private updateHash;
    private onHashChange;
    private internalInitialization;
    private addResourceBundle;
    render(): any[];
}
