import { AutomaticFacetGenerator, SearchStatus, SearchStatusState } from '@coveo/headless';
import { InitializableComponent } from '../../../../utils/initialization-utils';
import { Bindings } from '../../atomic-search-interface/atomic-search-interface';
/**
 * The `atomic-automatic-facet-generator` is a component that renders the facets from
 * the automatic facets feature. Unlike regular facets, which need to be explicitly defined
 * and requested in the query, automatic facets are dynamically generated by the index
 * in response to the search query.
 *
 * **Note:** This component renders one or more [automatic facets](https://docs.coveo.com/en/atomic/latest/reference/components/atomic-automatic-facet/) based on the `desiredCount` property.
 *
 * To learn more about the automatic facet generator feature, see: [About the Facet Generator](https://docs.coveo.com/en/n9sd0159/).
 */
export declare class AtomicAutomaticFacetGenerator implements InitializableComponent {
    bindings: Bindings;
    error: Error;
    automaticFacetGenerator: AutomaticFacetGenerator;
    private automaticFacetGeneratorState;
    searchStatus: SearchStatus;
    searchStatusState: SearchStatusState;
    /**
     * The desired count of automatic facets.
     *
     * Minimum: `1`
     * Maximum: `20`
     * @defaultValue `5`
     */
    desiredCount: number;
    /**
     * The desired number of automatically generated facet values.
     *
     * Minimum: `1`
     * @defaultValue `8`
     */
    numberOfValues: number;
    private collapseFacetsAfter;
    initialize(): void;
    updateCollapseFacetsDependingOnFacetsVisibility(collapseAfter: number, numberOfVisibleFacets: number): Promise<void>;
    private validateProps;
    private shouldCollapseFacet;
    render(): any[];
}
